name: Clojure CI

on:
  push:
    branches: [ master, devel ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - uses: DeLaGuardo/setup-clojure@3.1
      with:
        tools-deps: '1.10.1.763'

    - name: Cache node modules
      uses: actions/cache@v2.1.3
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-


    - name: Cache maven
      uses: actions/cache@v2.1.3
      env:
        cache-name: cache-maven
      with:
        path: ~/.m2
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/deps.edn') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}-

    - name: Cache gitlibs
      uses: actions/cache@v2.1.3
      env:
        cache-name: cache-gitlibs
      with:
        path: ~/.gitlibs
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/deps.edn') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}-

    - name: npm install
      run: npm install

    - name: Run Clojure tests
      run: lein test

    - name: Run Clojurescript tests
      run: |
        npx shadow-cljs compile node-test
        node target/node-test.js

